[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
exclude = ["notebooks/*", ".venv", ".git"]

[tool.ruff.lint]
select = ["E","F","I","UP","B","C4","SIM"]
ignore = ["UP006","UP007"]

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["src"]
