[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B","C4","SIM"]
ignore = []
exclude = ["/.venv"]

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["src"]
