data:
  train_path: data/train.csv
  target: target_churn
  id_col: customer_id
  valid_size: 0.2
  random_state: 42

model:
  type: "xgb"
  params:
    n_estimators: 1500
    learning_rate: 0.03
    max_depth: 6
    subsample: 0.9
    colsample_bytree: 0.9
    reg_lambda: 1.0
    random_state: 42

cv:
  folds: 5
  shuffle: true
  random_state: 42

calibration:
  method: "isotonic"

thresholding:
  k_fraction: 0.1
  budget: null
  cps: 2.0
  ltv: 100.0

plots:
  save_dir: reports/figures
