data:
  train_path: data/train.csv
  target: target_churn
  id_col: customerID
  valid_size: 0.2
  random_state: 42
model:
  type: "lgbm"
  params:
    n_estimators: 1200
    learning_rate: 0.03
    num_leaves: 63
    subsample: 0.9
    colsample_bytree: 0.9
    reg_lambda: 1.0
    random_state: 42
calibration:
  method: "isotonic"
thresholding:
  k_fraction: 0.1
  cps: 2.0
  ltv: 100.0
plots:
  save_dir: reports/figures
